### ISSUE TITLE
Improve support for SVG icons

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/plugin-api#3]
changing line 31 from const isTerriaJsPlugin = packageName ? packageName.startsWith("terriajs-plugin-") : false
to const isTerriaJsPlugin = packageName ? !!packageName.match(/terriajs-.*plugin/) : false;

**Comment by na9da** [comment]
PR: https://github.com/TerriaJS/vic-digital-twin/pull/363

**Comment by AnaBelgun** [comment]
PR merged
